// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const supabaseUrl = "https://tqrtzrnmizqmebopnknq.supabase.co";
const supabaseKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRxcnR6cm5taXpxbWVib3Bua25xIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzI2NDQ1MTIsImV4cCI6MjA0ODIyMDUxMn0.7vUWzyuw1S0gBgf9cI9-xsjSqMPRqP8ivVUxbAYmA9U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(supabaseUrl, supabaseKey);